"""
OpenFDA
DAG auto-generated by Astro Cloud IDE.
"""

from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime, timedelta
import pandas as pd
import requests

# Function to generate query URL for a specific month and year
def generate_query_url(year, month):
    start_date = f"{year}{month:02d}01"
    end_date = f"{year}{month:02d}{(datetime(year, month, 1) + timedelta(days=31)).replace(day=1) - timedelta(days=1):%d}"
    query = f"https://api.fda.gov/drug/event.json?search=patient.drug.medicinalproduct:%22sildenafil+citrate%22+AND+receivedate:[{start_date}+TO+{end_date}]&count=receivedate"
    return query

# Function to fetch data from the API and save it to XCom
def fetch_openfda_data(**kwargs):
    from airflow.operators.python import get_current_context
    
    ti = kwargs['ti']
    context = get_current_context()
    execution_date = context['logical_date']
    year = execution_date.year
    month = execution_date.month

    query_url = generate_query_url(year, month)
    response = requests.get(query_url)

    if response.status_code == 200:
        data = response.json()
        df = pd.DataFrame(data['results'])
        df['time'] = pd.to_datetime(df['time'])
        # Group by week and sum the count column
        weekly_sum = df.groupby(pd.Grouper(key='time', freq='W'))['count'].sum().reset_index()
        weekly_sum["time"] = weekly_sum["time"].astype(str)
        print(weekly_sum.info())
        print(weekly_sum.head())
    else:
        weekly_sum = pd.DataFrame([])  # Return empty DataFrame if request fails

    # Push the DataFrame to XCom
    ti.xcom_push(key='openfda_data', value=weekly_sum.to_dict())

def save_to_bigquery(**kwargs):
    from pandas import DataFrame
    from pandas_gbq import to_gbq

    ti = kwargs['ti']

    # Dados de configuração
    GCP_PROJECT = "meu-projeto-471401"
    BQ_DATASET = "openfda"
    BQ_TABLE = "openfda_history"
    BQ_LOCATION = "US"

    # Recupera DataFrame via XCom
    data_dict = ti.xcom_pull(task_ids='fetch_openfda_data', key='openfda_data')
    if data_dict:
        df = DataFrame.from_dict(data_dict)
        destino = f"{BQ_DATASET}.{BQ_TABLE}"
        to_gbq(
            df, 
            destination_table=destino, 
            project_id=GCP_PROJECT,
            if_exists='append',
            location=BQ_LOCATION
        )

# Define the DAG
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    'fetch_openfda_data_monthly',
    default_args=default_args,
    description='Retrieve OpenFDA data monthly',
    schedule='@monthly',
    start_date=datetime(2020, 11, 1),
    catchup=True,
    max_active_tasks=1
)


fetch_task = PythonOperator(
    task_id='fetch_openfda_data',
    python_callable=fetch_openfda_data,
    dag=dag,
)

save_data_task = PythonOperator(
    task_id='save_to_bigquery',    
    python_callable=save_to_bigquery,
    dag=dag,
)

fetch_task >> save_data_task

